name: room_decorator
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Core Flutter
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # AR Capabilities
  arcore_flutter_plugin: ^0.1.0  # For Android
  ar_flutter_plugin: ^0.7.3      # Cross-platform AR
  arkit_plugin: ^1.0.7           # For iOS

  # 3D Models & Rendering
  model_viewer_plus: ^1.7.0
  vector_math: ^2.1.4

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Navigation
  go_router: ^12.1.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # Image Handling
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  screenshot: ^2.1.0

  # UI Components
  flutter_colorpicker: ^1.0.3
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  # Utilities
  dartz: ^0.10.1              # Functional programming
  logger: ^2.0.2              # Logging
  permission_handler: ^11.0.1  # Permissions

  # Social Sharing
  share_plus: ^7.2.1

  # Network (if needed for catalog)
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  mocktail: ^1.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true